# Generated by Django 5.2.1 on 2025-05-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_authors_created_by_authors_unique_author_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='user',
            new_name='created_by',
        ),
    ]
